"""内置能力定义：能力元信息 + 可用性判断（基于是否具备 Embedding 能力）。"""

BUILTIN_CAPABILITIES = [
    {
        "id": "calculator",
        "name": "计算器",
        "source": "builtin",
        "requires": None,
        "desc": "安全计算数学表达式，支持四则运算、百分号换算与括号。",
        "example": "帮我计算 (137×0.85−20)÷3 等于多少",
        "code_key": "calculator",
    },
    {
        "id": "time_now",
        "name": "当前时间",
        "source": "builtin",
        "requires": None,
        "desc": "返回当前日期与时间。",
        "example": "现在几点？今天是几号？",
        "code_key": "time_now",
    },
    {
        "id": "web_search",
        "name": "网页搜索",
        "source": "builtin",
        "requires": None,
        "desc": "在网页上搜索关键词并返回前几条结果的标题与摘要。",
        "example": "搜索一下 Qwen3 的发布时间",
        "code_key": "web_search",
    },
    {
        "id": "run_command",
        "name": "命令执行（沙箱）",
        "source": "builtin",
        "requires": None,
        "desc": "在隔离沙箱中执行系统命令；无论审批策略如何，每次执行前都强制人工审批（HITL）。",
        "example": "帮我在沙箱里查看当前目录有哪些文件",
        "code_key": "run_command",
    },
    {
        "id": "big_output",
        "name": "大输出演示（落盘）",
        "source": "builtin",
        "requires": None,
        "desc": "生成一段超大文本（5000+ 字符）触发「大文件落盘」演示：正文写盘、上下文只留指针，页面出现落盘卡片。",
        "example": "用大输出演示工具生成一段大文件文本",
        "code_key": "big_output",
    },
    {
        "id": "memory",
        "name": "长期记忆",
        "source": "builtin",
        "requires": "embeddings",
        "desc": "跨会话长期记忆：写入（分类/重要性/去重）+ 按需召回（规范化注入块 + 老化提示）；支持全局常驻记忆（会话启动注入 system）。",
        "example": "记住：我喜欢深色主题，主色是紫色",
        "code_key": "memory",
    },
]
